# Generated by Django 3.2.12 on 2022-02-15 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='author_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
